# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Chloe Relf"                                # Your name
  description: "MPH Student | Population Health Research"   # A brief slogan (optional)
  image: img/IMG_3010 2.jpg
  
  favicon: img/convert.jpg
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/convert.jpg
    
    # your sub-pages
    left:
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/chloe-relf/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.cer92@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
    center: |
    right: |
  
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true